name: Teardown Environment

runs:
  using: "composite"
  steps:
    - name: Destroy Terraform (AWS)
      if: always()
      run: docker-compose -f docker-compose.dev-terraform.yml run --rm terraform destroy -input=false -auto-approve

    - name: Teardown local test environment
      if: always()
      run: docker-compose -f docker-compose.dev-env.yml down -v --rmi local --remove-orphans
  