version: '3.7'

networks:
  default:
    name: mydomain-api

services:
  local-db:
    image: mysql:5.7
    restart: unless-stopped
    networks:
      - default
    ports:
      - "30000:3306"
    volumes:
      - localdbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: localdefaultdb
  local-db-migrations:
    depends_on:
      - local-db
    networks:
      - default
    image: flyway/flyway:7.15
    volumes:
      - ./db/sql:/flyway/sql
      - ./db/config:/flyway/conf
    command: migrate -connectRetries=20
    environment:
      FLYWAY_EDITION: community
      FLYWAY_CONFIG_FILES: /flyway/conf/application.conf
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
  localstack:
    image: localstack/localstack:2.2
    networks:
      - default
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    volumes:
      - localstackdata:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - '~/.ca_certs:/tmp/certs'
    environment:    
      - SERVICES=s3,sns,sqs,sts
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - DEFAULT_REGION=eu-west-1
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
  wiremock:
    image: wiremock/wiremock:3.3.1
    ports:
      - "8081:8080"
      - "8443:8443"
    volumes:
      - ./mocks:/home/wiremock
    command: --local-response-templating true

volumes:
  localdbdata:
  localstackdata:
