version: '3.7'

networks:
  mydomain-api:
    external: true

services:
  mydomain.api:
    networks:
      - mydomain-api
    image: mydomain.api
    build:
      context: .
      dockerfile: src/api/MyDomain.Api/Dockerfile
      args:
        CERT_FILE_PATH: ${CERT_FILE_PATH:-.ca_certs}
        CERT_FILE: ${CERT_FILE}
