version: '3.7'

networks:
  mydomain-api:
    external: true

services:
  mydomain.api:
    networks:
      - mydomain-api
    ports:
      - "1001:80"
      - "1002:443"
    env_file: docker-compose.env
