name: Build and Test

on: [pull_request]

env:
  SOURCE_DIRECTORY: "./src"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore $SOURCE_DIRECTORY
    - name: Build
      run: dotnet build $SOURCE_DIRECTORY
    - name: Linting
      run: |
        FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.base.sha }} HEAD)
        dotnet format $SOURCE_DIRECTORY --verify-no-changes --no-restore --include $FILES_CHANGED --severity error -v diagnostic --report ./testresults/

  test:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write    

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Launch local test environment
      run: docker-compose -f docker-compose.dev-env.yml up -d
    - name: Init Terraform (AWS)
      run: docker-compose -f docker-compose.dev-terraform.yml run --rm terraform init
    - name: Apply Terraform (AWS)
      if: success()
      run: docker-compose -f docker-compose.dev-terraform.yml run --rm terraform apply -input=false -auto-approve
    - name: Test with docker compose
      run: docker-compose -f docker-compose.test.yml up --build --exit-code-from test
    - name: Code Coverage
      uses: codecov/codecov-action@v3
      if: always()
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: test-results/*.trx
    - name: Destroy Terraform (AWS)
      if: always()
      run: docker-compose -f docker-compose.dev-terraform.yml run --rm terraform destroy -input=false -auto-approve
    - name: Teardown local test environment
      if: always()
      run: docker-compose -f docker-compose.dev-env.yml down -v --rmi local --remove-orphans
