name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet build ./src
    - name: Test with the dotnet CLI
      run: dotnet test ./src/tests/**/*.csproj --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults"
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: "TestResults/test-results.trx"

  test-results:
    runs-on: ubuntu-latest
    needs: build
    if: success() || failure()

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Unit and Integration Tests
        path: "TestResults/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: true

