name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet build ./src
    - name: Test with the dotnet CLI
      run: dotnet test ./src --logger:trx;LogFileName=test-results.trx;MethodFormat=Class;FailureBodyFormat=Verbose
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unit and Integration Tests
        path: "**/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: true

