name: Build and Test

on:
  pull_request:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      source_directory: "./src"

  lint:
    name: Lint
    needs: build
    uses: ./.github/workflows/linting.yaml
    with:
      source_directory: "./src"

  test:
    name: Test
    uses: ./.github/workflows/test.yaml
    with:
      application_name: ${{ vars.APPLICATION_NAME }}
      application_version: "1.0.${{github.run_number}}"
    secrets:
      inherit

  test_report:
    name: Test Report
    needs: test
    uses: ./.github/workflows/test-report.yaml
    secrets:
      inherit

  deploy_to_test:
    name: Deploy to test
    needs: [ build, test ]
    uses: ./.github/workflows/deploy.yaml
    with:
      application_name: ${{ vars.APPLICATION_NAME }}
      application_version: "1.0.${{github.run_number}}"
      environment: "test"
    secrets:
      inherit
