name: Build and Test

on:
  pull_request:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  kube:
    name: Kubectl
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f
        with:
          version: '1.30.2'

  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      source_directory: "./src"

  lint:
    name: Lint
    needs: build
    uses: ./.github/workflows/linting.yaml
    with:
      source_directory: "./src"

  test:
    name: Test
    uses: ./.github/workflows/test.yaml
    with:
      application_name: ${{ vars.APPLICATION_NAME }}
      application_version: "1.0.${{github.run_number}}"
    secrets:
      inherit

  test_report:
    name: Test Report
    needs: test
    uses: ./.github/workflows/test-report.yaml

  deploy_to_test:
    name: Deploy to test
    needs: [ build, test ]
    uses: ./.github/workflows/deploy.yaml
    with:
      application_name: ${{ vars.APPLICATION_NAME }}
      application_version: "1.0.${{github.run_number}}"
      environment: "test"
    secrets:
      inherit
