name: Test Report Badge

on:
  workflow_call:
    inputs:
      test_result_json:
        required: true
        type: string
    secrets:
      GIST_TOKEN:
        required: true

jobs:
  test_report_badge:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write
      
    steps:
    - name: Set badge color
      shell: bash
      run: |
        case ${{ fromJSON( inputs.test_result_json ).conclusion }} in
          success)
            echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
            ;;
          failure)
            echo "BADGE_COLOR=800000" >> $GITHUB_ENV
            ;;
          neutral)
            echo "BADGE_COLOR=696969" >> $GITHUB_ENV
            ;;
        esac
  
    - name: Create badge
      uses: emibcn/badge-action@v2.0.2
      with:
        label: Tests
        status: '${{ fromJSON( inputs.test_result_json ).formatted.stats.tests }} tests, ${{ fromJSON( inputs.test_result_json ).formatted.stats.runs }} runs: ${{ fromJSON( inputs.test_result_json ).conclusion }}'
        color: ${{ env.BADGE_COLOR }}
        path: tests.svg

    - name: Upload badge to Gist
      uses: andymckay/append-gist-action@0.2
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gistURL: https://gist.github.com/matteus6007/bcdf0ee6170070c0fcc68059569e76a7
        file: tests.svg
