name: Test Report

on:
  workflow_call:
    outputs:
      test_result_json:
        description: "Test Result JSON"
        value: ${{ jobs.test_report.outputs.test_result_json }}

jobs:
  test_report:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    outputs:
      test_result_json: ${{ steps.test-results.outputs.json }}

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
      
    - name: Publish Test Results
      id: test-results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        check_run_annotations_branch: "*"
        files: "artifacts/**/*.trx"
