name: Test Report

on:
  workflow_run:
    workflows: ['Build and Test'] # runs after Build and Test workflow
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      with:
        name: Unit and Integration Tests
        artifact: test-results
        path: "**/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: false    
