name: Test

on:
  workflow_call:
    inputs:
      application_name:
        required: true
        type: string
      application_version:
        required: true
        type: string        
    secrets:
      CODECOV_TOKEN:
        required: true
      AUTHORIZATION_TOKEN:
        required: true
      SCHEMATHESIS_TOKEN:
        required: true
      PACT_BROKER_BASE_URL:
        required: true
      PACT_BROKER_TOKEN:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
      
    permissions:
      checks: write
      pull-requests: write

    outputs:
      application_name: ${{ inputs.application_name }}
      application_version: ${{ inputs.application_version }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Launch local test environment
      uses: ./.github/actions/launch-environment

    - name: Unit and integration tests
      uses: ./.github/actions/unit-integration-test
      with:
        test_results_path: "${{ github.workspace }}/testresults"
        codecov_token: ${{ secrets.CODECOV_TOKEN }}

    - name: Launch Application
      if: always()
      run: docker-compose up -d --build
    
    - name: Contract tests
      uses: ./.github/actions/contract-test
      with:
        schema_url: "http://localhost:1001/swagger/v1/swagger.yaml"
        application_name: ${{ inputs.application_name }}
        version: ${{ inputs.application_version }}
        report_path: ${{ github.workspace }}
        authorization_token: ${{ secrets.AUTHORIZATION_TOKEN }}
        schemathesis_token: ${{ secrets.SCHEMATHESIS_TOKEN }}
        pact_broker_base_url: ${{ secrets.PACT_BROKER_BASE_URL }}
        pact_broker_token: ${{ secrets.PACT_BROKER_TOKEN }}

    - name: Teardown local test environment
      uses: ./.github/actions/teardown-environment
